spring:
  application:
    name: beans-menu
  data:
    mongodb:
      uri: mongodb://${DB_HOST}/${DB_NAME}?authSource=admin&replicaSet=${DB_REPLICASET}
      database: beansmenu
    redis:
      host: ${REDIS_HOST:menu-redis-svc}
      port: ${REDIS_PORT:16379}
      password: ${REDIS_PASSWORD}
      logging: DEBUG
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG

server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable.redis: true
    distribution:
      percentiles:
        all:
          - 0.5
          - 0.95
          - 0.99
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: "beans-menu"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted