spring:
  application:
    name: beans-menu
  cache:
    type: simple
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin
      database: beansmenu
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG

server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles:
        all:
          - 0.5
          - 0.95
          - 0.99
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: "beans-menu"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted