spring:
  application:
    name: beans-menu
  cache:
    type: simple
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin
      database: beansmenu
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG
server:
  port: 8002
